# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ImGui_config = debug
  saffron_engine_2d_config = debug
  flocking_config = debug

else ifeq ($(config),release)
  ImGui_config = release
  saffron_engine_2d_config = release
  flocking_config = release

else ifeq ($(config),dist)
  ImGui_config = dist
  saffron_engine_2d_config = dist
  flocking_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ImGui saffron-engine-2d flocking

.PHONY: all clean help $(PROJECTS) Engine Engine/deps

all: $(PROJECTS)

Engine: Engine/deps saffron-engine-2d

Engine/deps: ImGui

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C build -f ImGui.make config=$(ImGui_config)
endif

saffron-engine-2d: ImGui
ifneq (,$(saffron_engine_2d_config))
	@echo "==== Building saffron-engine-2d ($(saffron_engine_2d_config)) ===="
	@${MAKE} --no-print-directory -C build -f saffron-engine-2d.make config=$(saffron_engine_2d_config)
endif

flocking: saffron-engine-2d ImGui
ifneq (,$(flocking_config))
	@echo "==== Building flocking ($(flocking_config)) ===="
	@${MAKE} --no-print-directory -C build -f flocking.make config=$(flocking_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f ImGui.make clean
	@${MAKE} --no-print-directory -C build -f saffron-engine-2d.make clean
	@${MAKE} --no-print-directory -C build -f flocking.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   saffron-engine-2d"
	@echo "   flocking"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"